services:
  db:
    container_name: odoo-db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${ODOO_DB_PORT}:5432"
    volumes:
      - ${ODOO_DB_PATH}:/var/lib/postgresql/data

  odoo:
    container_name: odoo-app
    image: odoo:18
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${ODOO_ENTERPRISE_PATH}:/mnt/enterprise
      - ${ADDONS_MAIN_PATH}:/mnt/addons-main
      - ${ADDONS_TEST_PATH}:/mnt/addons-test
      - ${ADDONS_MY_PATH}:/mnt/addons-my
      - ${ODOO_FILESTORE_PATH}:/var/lib/odoo
      - ${ODOO_CONFIG_PATH}:/etc/odoo/odoo.conf
