services:
  db:
    container_name: odoo-db
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  odoo:
    container_name: odoo-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./enterprise:/mnt/enterprise:ro
      - ./addons_main:/mnt/addons_main:ro
      - ./addons_test:/mnt/addons_test
      - ./addons_my:/mnt/addons_my
      - ./filestore:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8069/web/login >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
